### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' when requeuing a duplicated task

### ISSUE THREAD

**Issue by PauliusP17** [novacode-nl/odoo-celery#12]
I get this error every time if I try to requeue a duplicated task or tasks.

```Traceback (most recent call last):
  File "/opt/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo11/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo11/addons-celery/celery/wizard/celery_requeue_task.py", line 31, in action_requeue
    self.task_ids.action_requeue()
  File "/opt/odoo11/addons-celery/celery/models/celery_task.py", line 345, in action_requeue
    self._celery_call_task(task.user_id.id, task.uuid, task.model, task.method, _kwargs)
  File "/opt/odoo11/addons-celery/celery/models/celery_task.py", line 179, in _celery_call_task
    if not kwargs.get('_password'):
AttributeError: 'str' object has no attribute 'get'```

**Comment by bobslee** [comment]
Hi @PauliusP17 
What do you mean by **duplicated** task(s) ?

**Comment by PauliusP17** [comment]
Copied using Odoo's "Duplicate"

**Comment by bobslee** [comment]
Why would you like to duplicate/copy a task in the first place?

**Comment by PauliusP17** [comment]
Not really sure, I was simply duplicating to see how requeuing a lot of tasks will be handled.

Perhaps Duplicate and Create in general should be disabled, because even as an admin when I click create, most of the fields in the task form are read-only, so you can't really create a valid task anyway :)

**Comment by bobslee** [comment]
Thanks and I agree. You made valid point about the Create and Duplicate.
So I already disabled this in the form view (see referenced commit).

This issue can now be closed?

**Comment by PauliusP17** [comment]
Yes! Thanks :)
